language: java
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - alejandro5320@gmail.com
script:
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=alemoyaa -Dsonar.login=$SONAR

