language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
- mvn test --settings settings.xml
- if errorLevel 1 goto error
#Test unitario y de integracion en develop
- mvn verify --settings settings.xml
- exit
- :error
- echo .....=====......
